#ifndef PROCEDURAL_MODELING_LINEAR_EQUATION_SOLVER_H
#define PROCEDURAL_MODELING_LINEAR_EQUATION_SOLVER_H

void loadTestGraph();
void testLinearIneq();

#endif //PROCEDURAL_MODELING_LINEAR_EQUATION_SOLVER_H
